config/routes.rb
Rails.application.routes.draw do
  resources :messages

  mount API::Base, at: "/"
  mount GrapeSwaggerRails::Engine, at: "/documentation"

  get "message/important", to: "messages#important_box", as: "message_important_box"
  get "message/sent", to: "messages#sent_box", as: "message_sent_box"
  get "message/archived", to: "messages#archived_box", as: "message_archived_box"

  post "message/mass_action", to: "messages#mass_action", as: "mass_action"
  get "message/important/:id", to: "messages#make_important", as: "message_make_important"

  devise_for :users
  root to: "messages#index"
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :author,      class_name: "User", optional: true
  belongs_to :destinatary, class_name: "User", optional: true

  attr_accessor :destinatary_nickname

  validates_presence_of :title, :content
  validate :destinatary_exist?, on: :create

  def destinatary_exist?
    destinatary = User.find_by_nickname(destinatary_nickname)
    destinatary.present? ? self.destinatary_id = destinatary.id :
      errors.add(:destinatary_nickname, "can't be found!")
  end

  def read_now
    return if self.read
    self.update_attributes(read: true, read_date: DateTime.now)
    ActionCable.server.broadcast 'messages',
      status: 'saved', id: id, html: render_message
  end

  def important_now
    self.toggle(:important).save
    ActionCable.server.broadcast 'messages',
      status: 'saved', id: id, html: render_message
  end

  def archive_now
    self.update_attributes(archived: true, archive_date: DateTime.now)
    ActionCable.server.broadcast 'messages', status: 'deleted', id: id
  end

  def unarchive_now
    self.update_attributes(archived: false, archive_date: nil)
  end

  scope :current_user_inbox, lambda { |current_user|
    where(destinatary: current_user, archived: false).order(
      'created_at desc').includes(:author)
  }

  scope :current_user_archived, lambda { |current_user|
    where(destinatary: current_user, archived: true).order(
      'created_at desc').includes(:author)
  }

  scope :current_user_sent, lambda { |current_user|
    where(author: current_user).order(
      'created_at desc').includes(:destinatary)
  }

  scope :current_user_important, lambda { |current_user|
    where(destinatary: current_user, important: true).order(
      'created_at desc')
  }

  scope :current_user_unread, lambda { |current_user|
    where(destinatary: current_user, read: false, archived: false)
  }

  private

  def render_message
    ApplicationController.render(partial: 'messages/message_line',
      locals: { message: self })
  end
end

app/controllers/api/v1/messages.rb
module API
  module V1
    class Messages < Grape::API
      include API::V1::Defaults

      resource :messages do
        desc "Return all messages"
        get "", root: :messages do
          Message.all
        end

        desc "Return a Message"
        params do
          requires :id, type: String, desc: "ID of the
            Message"
        end
        get ":id", root: "message" do
          Message.where(id: permitted_params[:id]).first!
        end
      end
    end
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_message, :is_owner, only: [:show, :destroy, :make_important]
  before_action :set_messages, only: [:index, :new, :show,
    :sent_box, :archived_box, :important_box]

  def index
    @page_title = t('application_layout.title.inbox')
    @messages = Message.current_user_inbox(current_user)
  end

  def make_important
    @message.important_now
    redirect_to messages_url
  end

  def sent_box
    @page_title = t('application_layout.title.sent')
    @messages = Message.current_user_sent(current_user)
  end

  def important_box
    @page_title = t('application_layout.title.important')
    @messages = Message.current_user_important(current_user)
  end

  def archived_box
    @page_title = t('application_layout.title.archived')
    @messages = Message.current_user_archived(current_user)
  end

  def show
    @page_title = "Reading Message: #{@message.title}"
    @message.read_now if current_user == @message.destinatary
  end

  def new
    @page_title = t('application_layout.title.new_message')
    @message = Message.new
  end

  def create
    @message                      = Message.new(message_params)
    @message.author               = current_user
    @message.destinatary_nickname = params[:message][:destinatary_nickname]

    respond_to do |format|
      if @message.save
        format.html { redirect_to messages_url }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @message.archive_now
    respond_to do |format|
      format.html { redirect_to messages_url }
      format.json { head :no_content }
    end
  end

  def mass_action
    return unless params[:message_checkboxes].present?

    params[:message_checkboxes].each do |message_id|
      message = Message.find(message_id)

      case params[:commit]
      when t('message.view.message_list.button.mark_read')
        message.read_now
      when t('message.view.message_list.button.archive')
        message.archive_now
      else
        return
      end
    end
  end

  private
    def set_message
      @message = Message.find(params[:id])
    end

    def set_messages
      @messages_unread = Message.current_user_unread(current_user)
    end

    def message_params
      params.require(:message).permit(:title, :content, :author_id, :destinatary_id)
    end

    def is_owner
      redirect_to messages_path unless current_user == @message.destinatary or
        current_user == @message.author
    end
end

app/helpers/messages_helper.rb
module MessagesHelper
  def is_read_class(message)
    message.read ? "normal_message" : "new_message"
  end

  def is_read_icon(message)
    unless message.read
      content_tag(:i, "", class: ["fa", "fa-envelope"])
    end
  end

  def is_important_icon(message)
    if message.important
      content_tag(:i, "", class: ["fa", "fa-star"])
    end
  end

  def new_messages_badge(messages)
    return unless messages.present?
    content_tag(:span, messages.count, class: ["label",  "label-danger", "pull-right"])
  end
end

app/views/messages/_message_line.html.erb
<tr class="<%= is_read_class(message) %> message"
  data-message-id="<%= message.id %>">
  <td class="inbox-small-cells">
    <%= check_box_tag "message_checkboxes[]", message.id,
      false, data: { checkbox_item: true } %>
  </td>
  <td class="inbox-small-cells">
    <%= is_read_icon(message) %>
    <%= is_important_icon(message) %>
  </td>
  <td>
  <td><%= message.author.name %></td>
  <td>
    <%= link_to message do %>
      <%= message.title %>
    <% end %>
  </td>
  <td class="view-message text-right">
    <%= message.created_at.strftime("%d/%m/%Y at %I:%M %p") %></td>
  <td>
    <%= link_to message, method: :delete,
      class: "btn btn-danger btn-xs",
      title: t('message.view.message_line.archive_title'),
      data: { confirm: t('message.view.message_line.archive_confirm') } do %>
      <span class="glyphicon glyphicon-remove"></span>
    <% end %>

    <%= link_to message_make_important_path(message), remote: true,
      class: "btn btn-warning btn-xs",
      title: t('message.view.message_line.important_title') do %>
      <span class="glyphicon glyphicon-star"></span>
    <% end %>
  </td>
</tr>

app/views/messages/_messages_list.html.erb
<%= form_tag mass_action_path, remote: true do %>
  <div class="mail-option">
    <div class="chk-all">
      <input type="checkbox" class="mail-checkbox mail-group-checkbox" id="main_checkbox_list">
      <div class="btn-group">
        <a data-toggle="dropdown" href="#" class="btn mini all" aria-expanded="false">
          All <i class="fa fa-angle-down "></i>
        </a>
      </div>
    </div>

    <div class="btn-group">
      <%= submit_tag t('message.view.message_list.button.archive'),
        class: "btn btn-success",
        data: { disable_with: t('message.view.message_list.button.disabled_with') } %>
      <%= submit_tag t('message.view.message_list.button.mark_read'),
        class: "btn btn-danger",
        data: { disable_with: t('message.view.message_list.button.disabled_with') }  %>
    </div>
  </div>

  <table class="table table-inbox table-hover">
    <tbody class="messages">
      <% @messages.each do |message| %>
        <%= render partial: 'message_line', locals: { message: message } %>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/messages/archived_box.html.erb
<%= render partial: 'messages_list' %>

app/views/messages/important_box.html.erb
<%= render partial: 'messages_list' %>

app/views/messages/index.html.erb
<style type="text/css">
  .new_message {
      font-weight: bold;
  }

  .new_message {
  }
</style>

<p id="notice"><%= notice %></p>

<h1>Messages</h1>

<%= form_tag '/message/mass_action', remote: true do %>

  <table>
    <thead>
      <tr>
        <th></th>
        <th>Title</th>
        <th>Author</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody class="messages">
      <% @messages.each do |message| %>
        <%= render(partial: 'message_line', locals: { message: message }) %>
      <% end %>
    </tbody>
  </table>

  <%= submit_tag 'Mark as Read', data: { disable_with: 'Just a second...' } %>
  <%= submit_tag 'Archive', data: { disable_with: 'Just a second...' }  %>
<% end %>



<br>

<%= link_to 'New Message', new_message_path %>

app/views/messages/new.html.erb
<%= form_for(@message) do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2>
      <%= pluralize(@message.errors.count, "error") %>
      <%= t('message.view.new.model_error') %>
      </h2>

      <ul>
      <% @message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, class: "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_field :title, class: "form-control",
        placeholder: t('message.view.new.title_placeholder') %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :destinatary_nickname, "To",
      class: "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_field :destinatary_nickname, class: "form-control",
        placeholder: t('message.view.new.destiny_placeholder') %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :content, class: "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_area :content, rows: "10", cols: "30", class: "form-control",
        placeholder: t('message.view.new.content_placeholder') %>
    </div>
  </div>

  <div class="form-group">
      <div class="col-lg-offset-2 col-lg-10">
        <%= f.submit t('message.view.new.button'), class: "btn btn-send" %>
      </div>
  </div>
<% end %>

app/views/messages/sent_box.html.erb
<table class="table table-inbox table-hover">
  <tbody class="messages">
    <% @messages.each do |message| %>
      <tr>
        <td><%= message.destinatary.name %></td>
        <td>
          <%= link_to message do %>
            <%= message.title %>
          <% end %>
        </td>
        <td class="view-message  text-right">
          <%= message.created_at.strftime("%d/%m/%Y at %I:%M%p") %></td>
        <td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/messages/show.html.erb
<p>
  <strong><%= t('message.view.show.label.title') %></strong>
  <%= @message.title %>
</p>

<p>
  <strong><%= t('message.view.show.label.author') %></strong>
  <%= @message.author.name %>
</p>

<p>
  <strong><%= t('message.view.show.label.destinatary') %></strong>
  <%= @message.destinatary.name %>
</p>

<p>
  <strong><%= t('message.view.show.label.content') %></strong>
  <%= @message.content %>
</p>