config/routes.rb
Rails.application.routes.draw do
  resources :messages

  mount API::Base, at: "/"
  mount GrapeSwaggerRails::Engine, at: "/documentation"

  get "message/important", to: "messages#important_box", as: "message_important_box"
  get "message/sent", to: "messages#sent_box", as: "message_sent_box"
  get "message/archived", to: "messages#archived_box", as: "message_archived_box"

  post "message/mass_action", to: "messages#mass_action", as: "mass_action"
  get "message/important/:id", to: "messages#make_important", as: "message_make_important"

  devise_for :users
  root to: "messages#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Minibox</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= action_cable_meta_tag %>
  </head>

  <h1 align="center" class="base-title">
    <%= t('application_layout.title.main') %>
  </h1>

  <body>
    <div class="container">
      <div class="mail-box">
        <aside class="sm-side">
          <div class="user-head">
            <a class="inbox-avatar" href="javascript:;">
                <img  width="64" hieght="60" src="http://www.myiconfinder.com/uploads/iconsets/128-128-672f5b3d71b6fc40400e037ccdf3e034.png">
            </a>
            <div class="user-name">
                <h5><a href="#"><%= current_user.name %></a></h5>
                <span><a href="#"><%= current_user.email %></a></span>
            </div>
          </div>

          <div class="inbox-body">
            <%= link_to t('application_layout.button.compose'),
              new_message_path, title: t('application_layout.title.compose'),
                class: "btn btn-compose" %>
          </div>

          <ul class="inbox-nav inbox-divider">
            <li>
              <%= link_to messages_path do %>
                <i class="fa fa-inbox"></i> Inbox
                <%= new_messages_badge(@messages_unread) %>
              <% end %>
            </li>

            <li>
              <%= link_to message_sent_box_path,
                title: t('application_layout.title.sent') do %>
                <i class="fa fa-envelope-o"></i>
                <%= t('application_layout.tabs.sent') %>
              <% end %>
            </li>

            <li>
              <%= link_to message_important_box_path,
                title: t('application_layout.title.important') do %>
                <i class="fa fa-star-o"></i>
                <%= t('application_layout.tabs.important') %>
              <% end %>
            </li>

            <li>
              <%= link_to message_archived_box_path,
                title: t('application_layout.title.archived') do %>
                <i class="fa fa-trash-o"></i>
                <%= t('application_layout.tabs.archived') %>
              <% end %>
            </li>
          </ul>

          <div class="inbox-body text-center">
            <div class="btn-group">
              <%= link_to edit_user_registration_path, class: "btn mini btn-info",
                title: t('application_layout.button.edit_user') do %>
                <i class="fa fa-cog"></i>
              <% end %>
            </div>

            <div class="btn-group">
              <%= link_to destroy_user_session_path, class: "btn mini btn-danger",
                title: t('application_layout.button.logout'), method: :delete do %>
                <i class="fa fa-sign-out"></i>
              <% end %>
            </div>
          </div>
        </aside>

        <aside class="lg-side">
          <div class="inbox-head">
            <h3><%= @page_title %></h3>
            <form action="#" class="pull-right position">
              <div class="input-append">
                <input type="text" class="sr-input"
                  placeholder="<%= t('application_layout.search_placeholder') %>">
                <button class="btn sr-btn" type="button"><i class="fa fa-search"></i></button>
              </div>
            </form>
          </div>

          <div class="inbox-body">
            <%= yield %>
          </div>
        </aside>
      </div>
    </div>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t('devise.layout-title') %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= action_cable_meta_tag %>
  </head>

  <body class="devise-body">
    <div align="center" class="devise-box">
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </body>
</html>